name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: mrcroxx/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Plugins
          base: activity, community, repositories
          repositories_forks: yes
          repositories_affiliations: ""
          commits_authoring: mrcroxx@outlook.com, croxx@buaa.edu.cn, croxxpwn@gmail.com, mengyao@pingcap.com, mengyao.cs@gmail.com
          plugin_languages: yes
          plugin_languages_ignored: html, css, js, renderscript
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_notable: yes
          plugin_notable_filter: stars:>100
          plugin_notable_repositories: yes
